######################## default configuration ####################
#baseURL = "https://demo.gethugothemes.com/educenter/site/"
baseURL = "/"
uglyURLs = true
relativeURLs = true
title = "Engenharia de Computação"
theme = "educenter-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/Recife"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Site do Curso de Engenharia da Computação"
author = "Themefisher"
# contact info
address = "Rodovia PE-166, Km 03, Euno Andrade da Silva."
mobile = "+55 (81) 3320-6930"
email = "coord.computacao.uabj@ufrpe.br"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "-8.3270776"
map_longitude = "-36.4053281"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
#[[params.social]]
#title = "facebook"
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/uabj.ufrpe/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/Computacao-UABJ"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"


################################### Portugues language #####################################
[Languages.br]
languageName = "Br"
languageCode = "pt-br"
contentDir = "content/portugues"
weight = 1

[Languages.br.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2024 Coodenação de Engenharia da Computação"


################### French navigation ####################

# main menu
[[Languages.br.menu.main]]
name = "Sobre"
url = "about/"
weight = 1

[[Languages.br.menu.main]]
name = "Curso"
url = "course/"
weight = 2

[[Languages.br.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.br.menu.main]]
  parent = "Pages"
  name = "Professores"
  url = "teacher/"

  [[Languages.br.menu.main]]
  parent = "Pages"
  name = "Notícias"
  url = "notice/"

  [[Languages.br.menu.main]]
  parent = "Pages"
  name = "Eventos"
  url = "event/"

  [[Languages.br.menu.main]]
  parent = "Pages"
  name = "Cursos"
  url = "scholarship/"

  [[Languages.br.menu.main]]
  parent = "Pages"
  name = "Pesquisa"
  url = "research/"
  
#[[Languages.br.menu.main]]
#name = "blog"
#url = "blog/"
#weight = 4
  
[[Languages.br.menu.main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu

[[Languages.br.menu.footer]]
name = "Professores"
url = "teacher/"

[[Languages.br.menu.footer]]
name = "Notícias"
url = "notice/"

[[Languages.br.menu.footer]]
name = "Eventos"
url = "event/"

[[Languages.br.menu.footer]]
name = "Cursos"
url = "scholarship/"

[[Languages.br.menu.footer]]
name = "Pesquisa"
url = "research/"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

[Languages.en.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.en.menu.main]]
name = "course"
url = "course/"
weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "scholarship"
  url = "scholarship/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research/"
  
#[[Languages.en.menu.main]]
#name = "blog"
#url = "blog/"
#weight = 4
  
[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher/"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.en.menu.footer]]
name = "event"
url = "event/"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship/"

[[Languages.en.menu.footer]]
name = "research"
url = "research/"
